# -*- coding: utf-8 -*-
"""BDA_S08_Spark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znRJoGM-aqQ4oo7Oh3UrKGqGLwyKYkq0

# Session 8 Part 1: PySpark in Google Colab
"""

!pip install pyspark==4.1.2

# from pyspark.sql import SparkSession
# spark = SparkSession.builder.appName('SparkByExamples.com').getOrCreate()

from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("Session08Part01")
    .master("local[*]")
    .getOrCreate()
)

spark

students = [
    ("Ava", "Data Analytics", 92),
    ("Nikos", "Data Engineering", 85),
    ("Maya", "Data Analytics", 78),
    ("Leo", "Business", 88),
    ("Iris", "Data Engineering", 95),
]

columns = ["name", "track", "score"]

df = spark.createDataFrame(students, columns)

df.show()



"""Spark prints a table with name, track, and score."""

students = [
    ("Ava", "Data Analytics", 92),
    ("Nikos", "Data Engineering", 85),
    ("Maya", "Data Analytics", 78),
    ("Leo", "Business", 88),
    ("Iris", "Data Engineering", 95),
    ("Elena", "Business", 81),
    ("Omar", "Data Analytics", 90),
]

df = spark.createDataFrame(students, columns)

df.show()

"""7. Inspect the DataFrame"""

df.printSchema()
print("Rows:", df.count())
print("Columns:", df.columns)

"""What this shows:

printSchema() shows column names and inferred data types.

1.   printSchema() shows column names and inferred data types.
2.   count() counts rows.
3.   columns lists the column names.

Checkpoint question:

Which command is an action: printSchema, count, or columns?

count() is the clearest action here because it asks Spark to compute a result from the data.

Checkpoint question:
Why is checking the schema useful before writing filters or calculations?

The schema tells you which columns exist and what data type Spark thinks each column contains. This helps you avoid mistakes such as doing numeric comparisons on text columns.

# 8. Select columns
"""

df.select("name", "score").show()

"""Checkpoint question:

Does select("name", "score") change the original df?

No. Spark DataFrame operations return a new DataFrame. The original df still has all of its columns unless you assign the selected result to a variable.

Task: Show only the name and track columns.
"""

df.select("name", "track").show()

"""# 9. Select with expressions and conditions

select can do more than choose existing columns. It can also show calculated expressions.
"""

from pyspark.sql.functions import col, when

df.select(
    "name",
    "score",
    (col("score") + 5).alias("score_plus_5")
).show()

"""Checkpoint question:

Why do we use alias("score_plus_5") here?

The expression col("score") + 5 would otherwise have a long generated name. alias gives the calculated column a clear name in the output.
"""

df.select("name", "score").show()

"""You can also use a condition inside select:"""

df.select(
    "name",
    "track",
    "score",
    when(col("score") >= 85, "pass").otherwise("review").alias("result")
).show()

"""What this shows:



1.   when(...) checks a condition.
2.   otherwise(...) gives the value when the condition is false.
3.   alias("result") names the new output column.

Checkpoint question:

Does this conditional select permanently add the result column to df?

No. It only shows a selected output with a calculated column. If you want to keep the new column, use withColumn and assign the result to a variable.

Task: Select name, score, and a new column named score_level.

Use:

1.   "excellent" when the score is at least 90
2.   "good" when the score is at least 80
2.   "needs review" for all other scores
"""

df.select(
    "name",
    "score",
    when(col("score") >= 90, "excellent")
    .when(col("score") >= 80, "good")
    .otherwise("needs review")
    .alias("score_level")
).show()

"""# 10. Filter rows

Use filter to keep rows that match a condition:
"""

df.filter(df["score"] >= 90).show()

"""Checkpoint question:

What rows should this filter keep?

Show answer
It should keep only students whose score is greater than or equal to 90.

Task: Show students whose score is less than 85.
"""

df.filter(df["score"] < 85).show()



"""show students with name Maya"""

df.filter(df["name"] == "Maya").show()

"""What is the difference between this code and df.select("name", "track", "score")?

Show answer
df.select("name", "track", "score") shows those columns for every row. df.filter(col("score") >= 85).select(...) first keeps only high-score rows, then shows the selected columns.

Task: Show only the name and score columns for students in the Data Analytics track.
"""

df.filter(df["track"] == "Data Analytics").select("name", "score").show()

"""# 11. Create a new column

Import col and when:
"""

from pyspark.sql.functions import col, when

graded_df = df.withColumn(
    "result",
    when(col("score") >= 85, "pass").otherwise("review")
)

graded_df.show()

"""Checkpoint question:

Why do we save the result as graded_df instead of expecting df to change automatically?

Show answer
Spark DataFrames are immutable. withColumn returns a new DataFrame with the extra column, so assigning it to graded_df keeps the new version.

Task: Add a new column named score_plus_5 that adds 5 points to each score.

Show solution
"""

df.withColumn("score_plus_5", col("score") + 5).show()

"""# 12. Group and summarize

Use groupBy to summarize by category:
"""

df.groupBy("track").count().show()

"""Checkpoint question:

What does each row in this grouped result represent?

Show answer

Each row represents one track, plus the number of students in that track.

Now calculate average score by track:

the `agg` function is essential with `groupBy` because `groupBy` creates a `GroupedData` object, but it doesn't perform any calculations on its own. The `agg` function is then used to apply one or more aggregate functions (like `avg`, `sum`, `count`, `min`, `max`) to the grouped data.
"""

from pyspark.sql.functions import avg

df.groupBy("track").agg(avg("score").alias("average_score")).show()

"""Checkpoint question:

Why do we use alias("average_score")?

Show answer

Without an alias, Spark may show a generated column name such as avg(score). The alias gives the summary column a clean readable name.

Task: Find the maximum score in each track.
"""

from pyspark.sql.functions import max

df.groupBy("track").agg(max("score").alias("max_score")).show()

df.groupBy("track").agg(max("score")).show()

"""# 13. Exercise 1: PySpark student summary

Create a final Colab section called:

## Exercise 1

Your notebook should:

1.  Install PySpark.
2.  Start a Spark session.
3.  Create a DataFrame with at least 8 students.
    Include these columns:
    *   name
    *   track
    *   score
    *   hours_studied
4.  Print the schema.
5.  Show the first 5 rows.
6.  Filter students with score >= 85.
7.  Add a result column with pass or review.
8.  Group by track and show:
    *   number of students
    *   average score
    *   average hours studied
9.  Stop Spark at the end.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, col, count, when


spark = (
    SparkSession.builder
    .appName("Session08Exercise01")
    .master("local[*]")
    .getOrCreate()
)

students = [
    # TODO: add at least 8 rows
    ("Ava", "Data Analytics", 92, 40),
    ("Nikos", "Data Engineering", 85, 50),
    ("Maya", "Data Analytics", 78, 45),
    ("Leo", "Business", 88, 55),
    ("Iris", "Data Engineering", 95, 60),
    ("Elena", "Business", 81, 50),
    ("Omar", "Data Analytics", 90, 67),
    ("Stelios", "Data Analytics", 88, 50),
    ("Dara", "Data Engineering", 89, 67),
]

columns = ["name", "track", "score", "hours_studied"]

df = spark.createDataFrame(students, columns)

# TODO: print schema
df.printSchema()

# TODO: show first 5 rows
df.show(5)

# TODO: filter high scores
df.filter(df["score"] >= 85).show()

# TODO: add result column
df.withColumn(
    "result",
    when(col("score") >= 85, "pass").otherwise("review")
).show()

# TODO: group by track
df.groupBy("track").agg(
    count("name").alias("number_of_students"),
    avg("score").alias("average_score"),
    avg("hours_studied").alias("average_hours_studied")
).show()

spark.stop()