# -*- coding: utf-8 -*-
"""session-08-homework-pyspark-analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KtsDBgAkMWTUI08GsNK01r3xO1Zutxu5
"""



"""### Session 8 | Homework

> In this homework, you will use PySpark in Google Colab to build a small SQL-style analytics report.

#### 1. Goal

You will:

- create a PySpark DataFrame in Colab
- add a calculated column
- register a temporary SQL view
- write analytics queries with Spark SQL
- explain one result in plain English
"""



"""### Your notebook should:

1. Install PySpark.
2. Start a Spark session.
3. Create a DataFrame with at least 12 rows.
4. Use a dataset about one of these topics:
   - online orders
   - student scores
   - movie ratings
   - app events
5. Add at least one calculated column.
6. Register a temporary SQL view.
7. Write at least 4 SQL queries.
8. Include at least one grouped summary with `GROUP BY`.
9. Include at least one sorted result with `ORDER BY`.
10. Stop Spark at the end.
"""

# 1. Install PySpark.

!pip install pyspark==4.1.2

# from pyspark.sql import SparkSession
# from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType
# from datetime import datetime

# # Initialize Spark Session (if not already done)
# spark = SparkSession.builder.appName("ColabSparkExamples").getOrCreate()

# 2. Start a Spark session.
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

# 3. Create a DataFrame with at least 12 rows.
# 4. Use a dataset about one of these topics:
#    - online orders
#    - student scores
#    - movie ratings
#    - app events

## online orders

columns_orders = ["order_id", "city", "product", "category", "quantity", "unit_price"]

data_orders = [
    (1001, "London", "Laptop", "Electronics", 1, 799.99),
    (1002, "Manchester", "Sci-Fi Novel", "Books", 2, 12.25),
    (1003, "London", "Headphones", "Electronics", 1, 120.00),
    (1004, "Plymouth", "Blender", "Home & Kitchen", 1, 45.99),
    (1005, "Plymouth", "Lip Balm", "Beauty", 3, 5.25),
    (1006, "Rhye", "Coffee Maker", "Home & Kitchen", 1, 89.99),
    (1007, "Manchester", "History Book", "Books", 1, 29.99),
    (1008, "London", "Smartphone", "Electronics", 1, 699.99),
    (1009, "Rhye", "Yoga Mat", "Sports", 2, 25.00),
    (1010, "Bournemouth", "Sunscreen", "Beauty", 2, 14.50),
    (1011, "Rhye", "Desk Lamp", "Home & Kitchen", 2, 19.99),
    (1012, "London", "Wireless Mouse", "Electronics", 5, 24.50)
]

df_orders = spark.createDataFrame(data_orders, columns_orders)
df_orders.show(12)

'''Expected output:
+--------+-----------+--------------+--------------+--------+----------+
|order_id|       city|       product|      category|quantity|unit_price|
+--------+-----------+--------------+--------------+--------+----------+
|    1001|     London|        Laptop|   Electronics|       1|    799.99|
|    1002| Manchester|  Sci-Fi Novel|         Books|       2|     12.25|
|    1003|     London|    Headphones|   Electronics|       1|     120.0|
|    1004|   Plymouth|       Blender|Home & Kitchen|       1|     45.99|
|    1005|   Plymouth|      Lip Balm|        Beauty|       3|      5.25|
|    1006|       Rhye|  Coffee Maker|Home & Kitchen|       1|     89.99|
|    1007| Manchester|  History Book|         Books|       1|     29.99|
|    1008|     London|    Smartphone|   Electronics|       1|    699.99|
|    1009|       Rhye|      Yoga Mat|        Sports|       2|      25.0|
|    1010|Bournemouth|     Sunscreen|        Beauty|       2|      14.5|
|    1011|       Rhye|     Desk Lamp|Home & Kitchen|       2|     19.99|
|    1012|     London|Wireless Mouse|   Electronics|       5|      24.5|
+--------+-----------+--------------+--------------+--------+----------+
'''

#  5. Add at least one calculated column. - online orders
from pyspark.sql.functions import col

df_orders = df_orders.withColumn("revenue", col("quantity") * col("unit_price"))
df_orders.show()

# 3. Create a DataFrame with at least 12 rows.
# 4. Use a dataset about one of these topics:
#    - online orders
#    - student scores
#    - movie ratings
#    - app events

## student scores

columns_scores = ["student_id", "student_name", "class_grade", "subject", "score", "passed"]

data_scores = [
    (1, "Koshala", "10th", "Math", 85, True),
    (1, "Koshala", "10th", "Science", 90, True),
    (1, "Koshala", "10th", "History", 88, True),
    (2, "Dora", "11th", "Math", 92, True),
    (2, "Dora", "11th", "Science", 48, False),
    (2, "Dora", "11th", "History", 75, True),
    (3, "Malcolm", "10th", "Math", 78, True),
    (3, "Malcolm", "10th", "Science", 82, True),
    (3, "Malcolm", "10th", "History", 61, True),
    (4, "Daniela", "11th", "Math", 95, True),
    (4, "Daniela", "11th", "Science", 98, True),
    (4, "Daniela", "11th", "History", 91, True)
]

df_scores = spark.createDataFrame(data_scores, columns_scores)
df_scores.show(12)

'''Expected output:
+----------+------------+-----------+-------+-----+------+
|student_id|student_name|class_grade|subject|score|passed|
+----------+------------+-----------+-------+-----+------+
|         1|     Koshala|       10th|   Math|   85|  true|
|         1|     Koshala|       10th|Science|   90|  true|
|         1|     Koshala|       10th|History|   88|  true|
|         2|        Dora|       11th|   Math|   92|  true|
|         2|        Dora|       11th|Science|   48| false|
|         2|        Dora|       11th|History|   75|  true|
|         3|     Malcolm|       10th|   Math|   78|  true|
|         3|     Malcolm|       10th|Science|   82|  true|
|         3|     Malcolm|       10th|History|   61|  true|
|         4|     Daniela|       11th|   Math|   95|  true|
|         4|     Daniela|       11th|Science|   98|  true|
|         4|     Daniela|       11th|History|   91|  true|
+----------+------------+-----------+-------+-----+------+

'''

# 3. Create a DataFrame with at least 12 rows.
# 4. Use a dataset about one of these topics:
#    - online orders
#    - student scores
#    - movie ratings
#    - app events

## movie ratings

columns_ratings = ["user_id", "movie_title", "genre", "rating", "review_year", "is_recommended"]

data_ratings = [
    (501, "The Matrix", "Sci-Fi", 5, 2026, True),
    (501, "Inception", "Sci-Fi", 4, 2026, True),
    (502, "The Matrix", "Sci-Fi", 3, 2025, False),
    (503, "Gladiator", "Action", 5, 2026, True),
    (504, "Interstellar", "Sci-Fi", 2, 2024, False),
    (505, "Gladiator", "Action", 4, 2025, True),
    (501, "The Dark Knight", "Action", 5, 2026, True),
    (502, "Inception", "Sci-Fi", 5, 2026, True),
    (503, "The Dark Knight", "Action", 4, 2025, True),
    (504, "The Matrix", "Sci-Fi", 4, 2026, True),
    (505, "Interstellar", "Sci-Fi", 5, 2026, True),
    (502, "The Dark Knight", "Action", 2, 2024, False)
]

df_ratings = spark.createDataFrame(data_ratings, columns_ratings)
df_ratings.show(12)

'''Expected output:
+-------+---------------+------+------+-----------+--------------+
|user_id|    movie_title| genre|rating|review_year|is_recommended|
+-------+---------------+------+------+-----------+--------------+
|    501|     The Matrix|Sci-Fi|     5|       2026|          true|
|    501|      Inception|Sci-Fi|     4|       2026|          true|
|    502|     The Matrix|Sci-Fi|     3|       2025|         false|
|    503|      Gladiator|Action|     5|       2026|          true|
|    504|   Interstellar|Sci-Fi|     2|       2024|         false|
|    505|      Gladiator|Action|     4|       2025|          true|
|    501|The Dark Knight|Action|     5|       2026|          true|
|    502|      Inception|Sci-Fi|     5|       2026|          true|
|    503|The Dark Knight|Action|     4|       2025|          true|
|    504|     The Matrix|Sci-Fi|     4|       2026|          true|
|    505|   Interstellar|Sci-Fi|     5|       2026|          true|
|    502|The Dark Knight|Action|     2|       2024|         false|
+-------+---------------+------+------+-----------+--------------+
'''

# 3. Create a DataFrame with at least 12 rows.
# 4. Use a dataset about one of these topics:
#    - online orders
#    - student scores
#    - movie ratings
#    - app events

## app events

columns_events = ["event_id", "user_id", "device_type", "event_type", "page_url", "session_duration"]

data_events = [
    ("ev_01", 101, "Mobile", "login", "/home", 12),
    ("ev_02", 101, "Mobile", "view_item", "/product/42", 45),
    ("ev_03", 102, "Tablet", "login", "/home", 8),
    ("ev_04", 103, "Desktop", "click_ad", "/promo", 3),
    ("ev_05", 101, "Mobile", "purchase", "/checkout/success", 110),
    ("ev_06", 102, "Tablet", "view_item", "/product/17", 60),
    ("ev_07", 102, "Tablet", "add_to_cart", "/cart", 15),
    ("ev_08", 104, "Mobile", "login", "/home", 5),
    ("ev_09", 104, "Mobile", "view_item", "/product/42", 120),
    ("ev_10", 103, "Desktop", "logout", "/home", 2),
    ("ev_11", 102, "Tablet", "purchase", "/checkout/success", 95),
    ("ev_12", 105, "Desktop", "login", "/home", 10)
]

df_events = spark.createDataFrame(data_events, columns_events)
df_events.show(12)

# 6. Register a temporary SQL view. - online orders
df_orders.createOrReplaceTempView("orders")

# 7. Write at least 4 SQL queries.

# online orders (using temporary SQL view)
# columns_orders = ["order_id", "city", "product", "category", "quantity", "unit_price", "revenue"]

spark.sql("""
    SELECT *
    FROM orders
""").show()

spark.sql("""
    SELECT order_id, city, product, revenue
    FROM orders
    WHERE revenue >= 50
""").show()

spark.sql("""
    SELECT order_id, city, product, revenue
    FROM orders
    WHERE city == "London"
""").show()

spark.sql("""
    SELECT
        city,
        COUNT(*) AS order_count,
        ROUND(SUM(revenue), 2) AS total_revenue
    FROM orders
    GROUP BY city
    ORDER BY total_revenue DESC
""").show()

# 8. Include at least one grouped summary with `GROUP BY`.

# SQL version:
spark.sql("""
    SELECT
      category,
      ROUND(AVG(revenue),2) AS average_revenue_SQL
    FROM orders
    GROUP BY category
""").show()

# DataFrame version:
from pyspark.sql.functions import avg
from pyspark.sql import functions as F # Since Python's standard library also has a function named round, it creates a name conflict when importing.

df_orders.groupBy("category").agg(
    F.round(avg("revenue"),2).alias("average_revenue_dataframe")
).show()

# 9. Include at least one sorted result with `ORDER BY`.

# spark.sql("""
#     SELECT
#         city,
#         ROUND(SUM(revenue), 2) AS total_revenue
#     FROM orders
#     GROUP BY city
#     ORDER BY total_revenue DESC
# """).show()

# SQL version:
spark.sql("""
    SELECT
      category,
      ROUND(AVG(revenue),2) AS average_revenue_SQL
    FROM orders
    GROUP BY category
    ORDER BY average_revenue_SQL DESC
""").show()

from pyspark.sql.functions import avg
from pyspark.sql import functions as F # Since Python's standard library also has a function named round, it creates a name conflict when importing.

df_orders.groupBy("category").agg(
    F.round(F.avg("revenue"), 2).alias("average_revenue_dataframe")
).orderBy(F.desc("average_revenue_dataframe")).show()

# 10. Stop Spark at the end.

spark.stop()